### PR TITLE
Small fixes

### LINKED ISSUE #5: Make Data Hub accessible
Make Data Hub accessible:

- [x] Change background color from gradient to one color (the dark one)
- [x] Increase Ship Log font size
- [x] Change Chat Contacts color. Now the color is too shiny (hard to read)
- [x] Add font size selection for the chat (small, medium, large)

Use this tool to find better colors and font sizes:
[https://snook.ca/technical/colour_contrast/colour.html#fg=02F6FE,bg=333333](https://snook.ca/technical/colour_contrast/colour.html#fg=02F6FE,bg=333333)

### PR DESCRIPTION
**Pull request by 5annaha**
* Better layout for messages
* Shorter titles
* Fix voting filters
* Fix artifact filters and sorters
* Better layout for voting

### CODE REVIEW

File: src/app/components/messages/messages.component.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class MessagesComponent implements OnInit, OnDestroy, AfterViewInit {
 			map(([users, { userFilter }, unseenMessages]) => {
 				const filter = userFilter.toLowerCase().trim();
 				const isHacker = Boolean(window.sessionStorage.getItem('hackerId'));
-
+				console.log("Filter", filter);
```
Comment (nicou) [inline src/app/components/messages/messages.component.ts]: Leftover `console.log`

**Review by nicou — APPROVED** [review]
